export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] };

export type BlogPost = {
  slug: string;
  title: string;
  metaDescription: string;
  keywords: string[];
  category: string;
  publishDate: string; // ISO date
  readTime: string;
  excerpt: string;
  content: ContentBlock[];
  relatedServices: { label: string; href: string }[];
  relatedPosts: string[];
};

// [label](href) inside any "p" text is parsed into a real link at render
// time (see src/components/blog/RichText.tsx) - internal hrefs use next/link,
// external ones open in a new tab. Keeps the data plain TypeScript (no JSX)
// while still giving every article real, contextual internal linking.

export const blogPosts: BlogPost[] = [
  {
    slug: "jeddah-airport-to-makkah-transfer-guide",
    title: "Jeddah Airport to Makkah: Complete Transfer Guide",
    metaDescription:
      "Everything you need to know about getting from Jeddah's King Abdulaziz International Airport (KAIA) to Makkah — distance, travel time, vehicle options and booking tips.",
    keywords: ["jeddah airport to makkah", "kaia to makkah transfer", "jeddah airport taxi", "umrah airport pickup"],
    category: "Airport Transfers",
    publishDate: "2026-08-01",
    readTime: "6 min read",
    excerpt: "Distance, travel time, vehicle options and what to expect when you land at Jeddah's King Abdulaziz International Airport for your Umrah journey.",
    content: [
      { type: "p", text: "For most pilgrims arriving from outside Saudi Arabia, King Abdulaziz International Airport (KAIA) in Jeddah is the first stop before Makkah. It's the busiest gateway for Umrah traffic, especially during peak season, so knowing what to expect before you land makes the first hour of your trip far less stressful." },
      { type: "h2", text: "How far is Jeddah Airport from Makkah?" },
      { type: "p", text: "The drive from KAIA to central Makkah is roughly 80-95 km depending on your hotel's location near the Haram, and takes about 60-90 minutes by road in normal traffic. During Ramadan or the Hajj season this can stretch longer, so it's worth building in extra time rather than cutting it close." },
      { type: "h2", text: "What happens after you land" },
      { type: "p", text: "After immigration and baggage claim, most pilgrims head to the dedicated Umrah pilgrim terminal area if travelling on an Umrah visa. If you've arranged a private transfer, your driver will typically wait in the arrivals hall with a name board — no need to queue for a taxi rank or negotiate a fare on the spot." },
      { type: "h2", text: "Choosing the right vehicle" },
      { type: "p", text: "The right vehicle depends mostly on group size and luggage. A sedan like a Camry or Ford Taurus comfortably suits 1-3 passengers with normal luggage; families of 5-7 usually prefer a van like the Hyundai Staria or Toyota Hiace; larger groups of pilgrims travelling together often book a Coaster bus. See our [full fleet](/fleet/) for exact seating and luggage capacity on each vehicle." },
      { type: "h2", text: "Booking your transfer in advance" },
      { type: "p", text: "Arranging your pickup before you fly means no waiting around in a crowded arrivals hall after a long flight. You can [book your Jeddah Airport transfer online](/book-online/) with your flight number, and we track it so your driver adjusts automatically if your flight is delayed." },
    ],
    relatedServices: [
      { label: "Jeddah Airport Transfer Service", href: "/services/airport-transfer/jeddah/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["makkah-to-madinah-by-road-guide", "umrah-packing-list", "first-time-umrah-guide"],
  },
  {
    slug: "madinah-airport-transfer-guide",
    title: "Madinah Airport Transfer Guide (AMAA)",
    metaDescription:
      "Arriving at Prince Mohammad Bin Abdulaziz Airport in Madinah? Here's what to expect, how far it is to Masjid an-Nabawi, and how to book a reliable transfer.",
    keywords: ["madinah airport transfer", "amaa airport taxi", "prince mohammad bin abdulaziz airport", "madinah to haram transfer"],
    category: "Airport Transfers",
    publishDate: "2026-08-02",
    readTime: "5 min read",
    excerpt: "What to expect landing at Prince Mohammad Bin Abdulaziz Airport (AMAA) and how to get to your Madinah hotel near Masjid an-Nabawi without hassle.",
    content: [
      { type: "p", text: "Many pilgrims choose to fly into Madinah first, visit Masjid an-Nabawi, and travel on to Makkah afterwards. If that's your plan, Prince Mohammad Bin Abdulaziz Airport (AMAA) is a smaller, calmer airport than Jeddah's KAIA, which makes the arrival experience noticeably easier." },
      { type: "h2", text: "Distance from AMAA to central Madinah" },
      { type: "p", text: "The airport sits about 15-20 km from Masjid an-Nabawi and most hotels in the central zone, so the drive is usually only 20-30 minutes — one of the shortest airport-to-city transfers in Saudi Arabia." },
      { type: "h2", text: "Onward travel to Makkah" },
      { type: "p", text: "After your time in Madinah, the road transfer to Makkah takes around 4-5 hours. Rather than arranging this separately, most of our pilgrims book both legs together — see our [Madinah to Makkah transfer guide](/blog/makkah-to-madinah-by-road-guide/) for what that journey involves." },
      { type: "h2", text: "Booking tips" },
      { type: "p", text: "Share your flight number when you [book online](/book-online/) so we can track it — if your flight is delayed, your driver adjusts automatically rather than you arriving to an empty arrivals hall. This matters more in Madinah than you'd think, since taxi availability at AMAA can be limited outside peak hours." },
    ],
    relatedServices: [
      { label: "Madinah Airport Transfer Service", href: "/services/airport-transfer/madinah/" },
      { label: "Madinah Ziyarat Tours", href: "/services/ziyarat-tours/" },
    ],
    relatedPosts: ["madinah-ziyarat-guide", "makkah-to-madinah-by-road-guide", "where-to-stay-in-madinah"],
  },
  {
    slug: "riyadh-to-makkah-transfer-guide",
    title: "Riyadh to Makkah: Transfer Options & Travel Time",
    metaDescription:
      "Flying into Riyadh before Umrah? Compare travel options from Riyadh to Makkah — distance, drive time, and why most pilgrims choose Jeddah instead.",
    keywords: ["riyadh to makkah transfer", "riyadh airport to makkah", "riyadh to makkah distance"],
    category: "Airport Transfers",
    publishDate: "2026-08-03",
    readTime: "5 min read",
    excerpt: "Riyadh isn't the usual gateway for Umrah, but if your flight lands there, here's what the onward journey to Makkah actually involves.",
    content: [
      { type: "p", text: "Riyadh is Saudi Arabia's capital and a major international hub, but it isn't on the west coast like Jeddah or Madinah — so the road journey onward to Makkah is significantly longer than the more common routes." },
      { type: "h2", text: "How far is it?" },
      { type: "p", text: "The distance from Riyadh to Makkah by road is roughly 870 km, which typically takes 8-9 hours to drive depending on stops and traffic. It's a doable journey in a comfortable vehicle, but most pilgrims flying into Riyadh choose to take a short domestic connecting flight to Jeddah instead, then transfer by road from there." },
      { type: "h2", text: "When a direct road transfer makes sense" },
      { type: "ul", items: [
        "You already have business or family reasons to land in Riyadh",
        "Your group prefers one long overland journey over a connecting flight",
        "You're combining Umrah with sightseeing in central Saudi Arabia",
      ] },
      { type: "p", text: "For a long-distance transfer like this, comfort matters — we recommend a Mercedes S-Class or GMC Yukon for the extra legroom and smoother ride on a multi-hour drive. Check our [full fleet](/fleet/) for options." },
      { type: "h2", text: "The more common route" },
      { type: "p", text: "If flexibility allows, flying into Jeddah and taking the much shorter [Jeddah Airport to Makkah transfer](/blog/jeddah-airport-to-makkah-transfer-guide/) (around 80-95 km) saves most of a day of travel." },
    ],
    relatedServices: [
      { label: "Riyadh Airport Transfer", href: "/services/airport-transfer/riyadh/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["jeddah-airport-to-makkah-transfer-guide", "makkah-madinah-distance-transport-compared"],
  },
  {
    slug: "alula-to-makkah-transport-guide",
    title: "AlUla to Makkah: Umrah Transport Guide",
    metaDescription:
      "Combining a visit to AlUla with Umrah? Here's the distance, travel time and transport options for getting from AlUla to Makkah.",
    keywords: ["alula to makkah", "alula umrah transport", "alula to makkah distance"],
    category: "Airport Transfers",
    publishDate: "2026-08-04",
    readTime: "4 min read",
    excerpt: "AlUla's heritage sites make a memorable add-on to an Umrah trip — here's how the transfer to Makkah actually works.",
    content: [
      { type: "p", text: "AlUla, home to the Hegra UNESCO World Heritage site, has become a popular addition to Saudi itineraries in recent years. If you're combining a visit there with Umrah, planning the transport link between the two matters — they're on opposite sides of the country's travel network." },
      { type: "h2", text: "Distance and travel time" },
      { type: "p", text: "The road distance from AlUla to Makkah is around 900 km, roughly 9-10 hours of driving. Most travellers combining both destinations either fly between AlUla and Jeddah/Madinah and arrange a shorter road transfer from there, or treat the long drive itself as part of the journey with an overnight stop." },
      { type: "h2", text: "Our recommendation" },
      { type: "p", text: "For most pilgrims, the smoothest combination is: fly into Madinah, complete your Ziyarat there, take a short flight or arranged transfer to AlUla for sightseeing, then fly onward to Jeddah for the final [short transfer into Makkah](/blog/jeddah-airport-to-makkah-transfer-guide/). This avoids two very long overland legs back to back." },
      { type: "p", text: "Whichever route you choose, [book your vehicle in advance](/book-online/) so it's waiting when you land, with the right capacity for your luggage and group size." },
    ],
    relatedServices: [
      { label: "AlUla Airport Transfer", href: "/services/airport-transfer/alula/" },
      { label: "Group Packages", href: "/services/group-packages/" },
    ],
    relatedPosts: ["jeddah-airport-to-makkah-transfer-guide", "madinah-airport-transfer-guide"],
  },
  {
    slug: "taif-airport-transfer-guide",
    title: "Taif Airport Transfer for Umrah Pilgrims",
    metaDescription:
      "Taif is a cooler, higher-altitude alternative gateway near Makkah. Here's what to know about transfers from Taif Airport for your Umrah trip.",
    keywords: ["taif airport transfer", "taif to makkah", "taif umrah taxi"],
    category: "Airport Transfers",
    publishDate: "2026-08-05",
    readTime: "4 min read",
    excerpt: "Taif's cooler mountain climate makes it a pleasant stopover — here's how the transfer to Makkah from Taif Airport compares.",
    content: [
      { type: "p", text: "Sitting at higher altitude in the Sarawat mountains, Taif offers noticeably cooler weather than Makkah, especially in summer — which is why some pilgrims add a short stay there before or after their Umrah." },
      { type: "h2", text: "Distance to Makkah" },
      { type: "p", text: "Taif is only about 90 km from Makkah, but the mountain road (Al-Hada Highway) descends through several switchbacks, so the drive takes around 1.5-2 hours rather than what the short distance might suggest." },
      { type: "h2", text: "What to expect on the drive" },
      { type: "p", text: "The Al-Hada road is scenic but winding, with sweeping viewpoints over the valley below. A comfortable, well-maintained vehicle with an experienced driver who knows the route makes a real difference here — this isn't a road to rush." },
      { type: "p", text: "If you're planning a Taif stopover as part of a longer trip, [get in touch](/book-online/) with your dates and we'll arrange the transfer both ways." },
    ],
    relatedServices: [
      { label: "Taif Airport Transfer", href: "/services/airport-transfer/taif/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["jeddah-airport-to-makkah-transfer-guide", "best-time-of-year-for-umrah"],
  },
  {
    slug: "complete-ziyarat-guide-makkah",
    title: "Complete Ziyarat Guide to Makkah's Holy Sites",
    metaDescription:
      "A guide to the most significant Ziyarat sites in and around Makkah — Jabal al-Nour, Jabal Thawr, Mina, Arafat and Muzdalifah — with practical visiting tips.",
    keywords: ["makkah ziyarat", "ziyarat sites makkah", "jabal al-nour", "jabal thawr", "mina arafat muzdalifah"],
    category: "Ziyarat Guides",
    publishDate: "2026-08-06",
    readTime: "7 min read",
    excerpt: "Beyond the Haram itself, Makkah is surrounded by historically significant sites well worth a guided visit during your stay.",
    content: [
      { type: "p", text: "While the heart of any Umrah trip is Masjid al-Haram, many pilgrims set aside a day to visit the historically significant sites around Makkah known collectively as Ziyarat. Seeing them with a knowledgeable local driver adds real context to places you've likely only read about." },
      { type: "h2", text: "Jabal al-Nour and the Cave of Hira" },
      { type: "p", text: "Jabal al-Nour ('Mountain of Light') is where the Cave of Hira is located, significant in Islamic history. It involves a steep climb on foot for those wishing to reach the cave itself — comfortable shoes and water are essential, and it's best attempted outside the midday heat." },
      { type: "h2", text: "Jabal Thawr" },
      { type: "p", text: "South of Makkah, Jabal Thawr is another historically significant mountain. Most visitors view it from the base rather than climbing, as the ascent is considerably more demanding than Jabal al-Nour." },
      { type: "h2", text: "Mina, Arafat and Muzdalifah" },
      { type: "p", text: "These three sites are central to the annual Hajj pilgrimage, but many Umrah visitors still like to see them. They're spread across a wider area, so a private vehicle covering all three in one guided trip is far more practical than trying to arrange separate visits." },
      { type: "h2", text: "Planning your Ziyarat day" },
      { type: "ul", items: [
        "Start early to avoid the midday heat, especially for Jabal al-Nour",
        "Wear comfortable, closed shoes if you plan to walk or climb",
        "Carry water and sun protection at all times",
        "A private vehicle lets you set your own pace between sites rather than following a fixed group schedule",
      ] },
      { type: "p", text: "We run guided [Ziyarat tours](/services/ziyarat-tours/) covering all of these sites with drivers who know the history and the practical logistics of each stop — [book your Ziyarat day](/book-online/) alongside your airport transfer to make the most of your time in Makkah." },
    ],
    relatedServices: [
      { label: "Ziyarat Tours", href: "/services/ziyarat-tours/" },
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["madinah-ziyarat-guide", "jabal-uhud-visit-guide", "best-time-to-visit-masjid-al-haram"],
  },
  {
    slug: "madinah-ziyarat-guide",
    title: "Madinah Ziyarat: Places to Visit & Transport Tips",
    metaDescription:
      "A practical guide to visiting Madinah's key Ziyarat sites beyond Masjid an-Nabawi — Quba Mosque, Jabal Uhud, and the Seven Mosques.",
    keywords: ["madinah ziyarat", "quba mosque", "jabal uhud", "seven mosques madinah"],
    category: "Ziyarat Guides",
    publishDate: "2026-08-07",
    readTime: "6 min read",
    excerpt: "Madinah's Ziyarat sites are spread further apart than Makkah's — here's how to see them all comfortably in a single guided trip.",
    content: [
      { type: "p", text: "Madinah's significant sites are more spread out than Makkah's, which makes a private vehicle the practical choice for seeing them without spending your whole visit walking between locations in the heat." },
      { type: "h2", text: "Quba Mosque" },
      { type: "p", text: "A short drive from central Madinah, Quba Mosque holds particular significance and is well worth an early-morning visit before the heat and crowds build up. Read our [dedicated Quba Mosque guide](/blog/quba-mosque-visit-guide/) for more detail." },
      { type: "h2", text: "Jabal Uhud" },
      { type: "p", text: "A little further out, Jabal Uhud is another historically important site with a visitor area at its base. See our [full Jabal Uhud guide](/blog/jabal-uhud-visit-guide/) for what to expect." },
      { type: "h2", text: "Masjid al-Qiblatain (Mosque of the Two Qiblas)" },
      { type: "p", text: "This mosque is historically notable for the change in the direction of prayer, and is a common stop on any Madinah Ziyarat tour." },
      { type: "h2", text: "Booking a Madinah Ziyarat day" },
      { type: "p", text: "Because these sites are scattered across the city and its outskirts, we recommend covering them all in one [guided Ziyarat tour](/services/ziyarat-tours/) rather than arranging separate taxis for each — it's both more efficient and considerably cheaper than piecing the day together yourself." },
    ],
    relatedServices: [
      { label: "Madinah Ziyarat Tours", href: "/services/ziyarat-tours/" },
      { label: "Madinah Airport Transfer", href: "/services/airport-transfer/madinah/" },
    ],
    relatedPosts: ["jabal-uhud-visit-guide", "quba-mosque-visit-guide", "where-to-stay-in-madinah"],
  },
  {
    slug: "jabal-uhud-visit-guide",
    title: "Jabal Uhud Visit Guide: History & How to Get There",
    metaDescription:
      "Planning a visit to Jabal Uhud in Madinah? Here's the history, what you'll see, and how to arrange transport there and back.",
    keywords: ["jabal uhud", "mount uhud madinah", "uhud visit guide"],
    category: "Ziyarat Guides",
    publishDate: "2026-08-08",
    readTime: "5 min read",
    excerpt: "One of Madinah's most historically significant sites, and a common stop on any Ziyarat itinerary.",
    content: [
      { type: "p", text: "Jabal Uhud sits on the outskirts of Madinah and is one of the most frequently visited sites on a Ziyarat itinerary, thanks to its deep historical significance and accessible visitor area at the base of the mountain." },
      { type: "h2", text: "Getting there" },
      { type: "p", text: "It's roughly a 15-20 minute drive from central Madinah, making it easy to combine with other nearby sites like Quba Mosque and Masjid al-Qiblatain in a single half-day trip." },
      { type: "h2", text: "What to expect" },
      { type: "p", text: "There's a dedicated visitor area with parking, and most people spend 30-45 minutes at the site. Mornings tend to be cooler and less crowded than midday." },
      { type: "h2", text: "Combining it with other sites" },
      { type: "p", text: "Rather than a standalone trip, most pilgrims include Jabal Uhud as part of a broader [Madinah Ziyarat tour](/blog/madinah-ziyarat-guide/) — one vehicle, one driver, covering everything in a logical order without backtracking across the city." },
    ],
    relatedServices: [
      { label: "Ziyarat Tours", href: "/services/ziyarat-tours/" },
    ],
    relatedPosts: ["madinah-ziyarat-guide", "quba-mosque-visit-guide"],
  },
  {
    slug: "quba-mosque-visit-guide",
    title: "Quba Mosque Visit: History & How to Get There",
    metaDescription:
      "A guide to visiting Quba Mosque in Madinah — significance, best time to go, and how to arrange transport from your hotel.",
    keywords: ["quba mosque", "masjid quba", "quba mosque madinah visit"],
    category: "Ziyarat Guides",
    publishDate: "2026-08-09",
    readTime: "4 min read",
    excerpt: "A short drive from central Madinah, Quba Mosque is one of the most commonly visited Ziyarat sites — here's what to know before you go.",
    content: [
      { type: "p", text: "Quba Mosque is one of the earliest mosques in Islamic history and sits a short distance from central Madinah, making it an easy and popular addition to any Ziyarat plan." },
      { type: "h2", text: "Best time to visit" },
      { type: "p", text: "Early morning is generally quieter and cooler than later in the day. If your schedule allows, going right after Fajr avoids both the heat and the larger crowds that build up through the morning." },
      { type: "h2", text: "Getting there" },
      { type: "p", text: "The mosque is a short 10-15 minute drive from most hotels near Masjid an-Nabawi. Rather than negotiating a taxi at the roadside, most pilgrims combine this with other nearby sites in a single [guided Ziyarat tour](/services/ziyarat-tours/) so the whole morning is planned out in advance." },
    ],
    relatedServices: [
      { label: "Ziyarat Tours", href: "/services/ziyarat-tours/" },
      { label: "Madinah Airport Transfer", href: "/services/airport-transfer/madinah/" },
    ],
    relatedPosts: ["jabal-uhud-visit-guide", "madinah-ziyarat-guide"],
  },
  {
    slug: "makkah-to-madinah-by-road-guide",
    title: "Makkah to Madinah by Road: Complete Guide",
    metaDescription:
      "Planning the intercity transfer between Makkah and Madinah? Here's the distance, travel time, route options and what to expect on the road.",
    keywords: ["makkah to madinah by road", "makkah madinah transfer", "makkah to madinah taxi"],
    category: "Makkah–Madinah Travel",
    publishDate: "2026-08-10",
    readTime: "6 min read",
    excerpt: "A door-to-door look at what the Makkah-Madinah road transfer actually involves — distance, timing, stops and vehicle choice.",
    content: [
      { type: "p", text: "The journey between Makkah and Madinah is one of the most common legs of any Umrah trip, and one of the most straightforward to plan well in advance." },
      { type: "h2", text: "Distance and travel time" },
      { type: "p", text: "The direct road distance is around 450 km, and the drive typically takes 4-5 hours depending on your exact pickup and drop-off points and how many rest stops you take along the way." },
      { type: "h2", text: "Choosing when to travel" },
      { type: "p", text: "Many pilgrims prefer an early morning or overnight departure to avoid daytime heat and traffic, especially in summer. See our guide on [the best time to travel between Makkah and Madinah](/blog/best-time-to-travel-makkah-madinah/) for a fuller comparison." },
      { type: "h2", text: "Rest stops along the way" },
      { type: "p", text: "The route has a number of well-serviced rest stops with prayer areas, food and restrooms, so the journey is comfortable even with a mid-trip break for Salah." },
      { type: "h2", text: "Which vehicle to choose" },
      { type: "ul", items: [
        "Sedan (Camry, Taurus) — 1-3 passengers, standard luggage",
        "Luxury sedan (S-Class, 7 Series) — smoother, quieter ride for longer comfort",
        "Van (Hiace, Staria, Starex) — families of 5-7 with more luggage",
        "Coaster bus — groups of 15+ travelling together",
      ] },
      { type: "p", text: "Whichever direction you're travelling, [book your Makkah-Madinah transfer](/book-online/) in advance so your vehicle and driver are confirmed well before your travel date." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer Service", href: "/services/makkah-madinah-transfer/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["best-time-to-travel-makkah-madinah", "makkah-madinah-distance-transport-compared"],
  },
  {
    slug: "best-time-to-travel-makkah-madinah",
    title: "Best Time to Travel Between Makkah and Madinah",
    metaDescription:
      "Should you travel between Makkah and Madinah in the morning, evening, or overnight? Here's how to time your intercity transfer.",
    keywords: ["best time makkah to madinah", "when to travel makkah madinah", "makkah madinah overnight transfer"],
    category: "Makkah–Madinah Travel",
    publishDate: "2026-08-11",
    readTime: "5 min read",
    excerpt: "Timing your Makkah-Madinah transfer well can make a 4-5 hour drive feel a lot shorter — here's what to consider.",
    content: [
      { type: "p", text: "The Makkah-Madinah road transfer takes roughly the same amount of time whenever you travel, but WHEN you go can make a real difference to comfort, especially outside the cooler winter months." },
      { type: "h2", text: "Early morning departures" },
      { type: "p", text: "Leaving shortly after Fajr means you arrive before the midday heat, and roads tend to be quieter than later in the day. This is our most commonly recommended slot for families and elderly travellers." },
      { type: "h2", text: "Overnight travel" },
      { type: "p", text: "Some pilgrims prefer to travel overnight, sleeping through most of the journey and arriving fresh in the early morning — particularly useful if you want to maximise daylight hours at your destination for Ziyarat or rest." },
      { type: "h2", text: "What to avoid" },
      { type: "p", text: "Midday departures in summer (roughly May-September) mean several hours of driving through peak heat, which is more taxing even inside an air-conditioned vehicle, especially for elderly or unwell travellers. See our tips for [elderly and disabled pilgrims](/blog/tips-for-elderly-disabled-pilgrims/) for more on planning around this." },
      { type: "p", text: "Whatever time suits your itinerary, [book your transfer](/book-online/) with your preferred pickup time and we'll confirm a driver accordingly." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
    ],
    relatedPosts: ["makkah-to-madinah-by-road-guide", "tips-for-elderly-disabled-pilgrims"],
  },
  {
    slug: "makkah-madinah-distance-transport-compared",
    title: "Makkah to Madinah: Distance, Time & Transport Options Compared",
    metaDescription:
      "Private car, shared shuttle, bus or train — comparing your options for travelling between Makkah and Madinah.",
    keywords: ["makkah madinah transport options", "haramain train vs taxi", "makkah madinah distance"],
    category: "Makkah–Madinah Travel",
    publishDate: "2026-08-12",
    readTime: "6 min read",
    excerpt: "Private transfer, shared shuttle, or the Haramain train — here's how the main options between Makkah and Madinah actually compare.",
    content: [
      { type: "p", text: "There's more than one way to travel between Makkah and Madinah, and the right choice depends on your budget, group size and how much you value flexibility over cost." },
      { type: "h2", text: "Private transfer" },
      { type: "p", text: "A private vehicle picks you up from your exact hotel and drops you at your exact destination, on your own schedule. It's the most comfortable and flexible option, particularly for families, groups with luggage, or anyone travelling with elderly or young members." },
      { type: "h2", text: "Haramain High Speed Railway" },
      { type: "p", text: "The Haramain train connects Makkah, Jeddah and Madinah at high speed and is a reasonable option for a single traveller without much luggage — though it doesn't take you door-to-door, so you'll still need transport to and from each station." },
      { type: "h2", text: "Shared shuttle / bus" },
      { type: "p", text: "The cheapest option, but on a fixed schedule with multiple stops, and less practical for families or anyone travelling with substantial luggage." },
      { type: "h2", text: "Our recommendation" },
      { type: "p", text: "For most pilgrims — especially families, groups, or anyone arriving straight off a long flight — a [private Makkah-Madinah transfer](/services/makkah-madinah-transfer/) is worth the difference in cost for the door-to-door convenience alone." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
      { label: "Group Packages", href: "/services/group-packages/" },
    ],
    relatedPosts: ["makkah-to-madinah-by-road-guide", "umrah-budget-guide"],
  },
  {
    slug: "miqat-points-explained",
    title: "Miqat Points Explained: A Complete Guide for Umrah Pilgrims",
    metaDescription:
      "What is a Miqat, which one applies to your route, and how do you arrange transport to stop there before continuing to Makkah?",
    keywords: ["miqat points", "miqat for umrah", "miqat boundary makkah"],
    category: "Miqat & Ihram",
    publishDate: "2026-08-13",
    readTime: "6 min read",
    excerpt: "Understanding which Miqat applies to your journey, and how to plan a comfortable stop there before entering Ihram.",
    content: [
      { type: "p", text: "One of the practical questions every pilgrim faces before Umrah is: which Miqat applies to my route, and how do I actually stop there? Getting this right matters, and getting the transport logistics right makes the process far less stressful." },
      { type: "h2", text: "What is a Miqat?" },
      { type: "p", text: "A Miqat is a designated boundary point where pilgrims intending Umrah or Hajj enter the state of Ihram before continuing to Makkah. Which Miqat applies to you generally depends on the direction you're travelling from — for specific rulings on your situation, it's best to confirm with a knowledgeable scholar or your group's guide." },
      { type: "h2", text: "Common Miqat points by route" },
      { type: "ul", items: [
        "Dhul Hulaifah (Abyar Ali) — the Miqat for those travelling from Madinah",
        "Al-Juhfah / Rabigh — commonly used by pilgrims arriving via Jeddah",
        "Qarn al-Manazil (As-Sayl) — for pilgrims arriving from the Riyadh/Najd direction",
        "Yalamlam — for pilgrims arriving from Yemen/the south",
      ] },
      { type: "h2", text: "Planning your transport around it" },
      { type: "p", text: "If you're travelling from Madinah, see our [Dhul Hulaifah Miqat guide](/blog/dhul-hulaifah-miqat-guide/) for exactly how that stop works. Wherever your Miqat is, a private transfer means your driver can wait while you change into Ihram and perform the intention, rather than rushing on a fixed shared-transport schedule." },
      { type: "p", text: "For more on preparing for the state of Ihram itself, see our guide on [what to know before your Miqat stop](/blog/entering-ihram-what-to-know/)." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["dhul-hulaifah-miqat-guide", "entering-ihram-what-to-know", "ihram-guide-men-women"],
  },
  {
    slug: "dhul-hulaifah-miqat-guide",
    title: "Dhul Hulaifah Miqat Guide (for Pilgrims Travelling from Madinah)",
    metaDescription:
      "A practical guide to stopping at Dhul Hulaifah (Abyar Ali), the Miqat for pilgrims travelling from Madinah to Makkah.",
    keywords: ["dhul hulaifah", "abyar ali miqat", "miqat from madinah"],
    category: "Miqat & Ihram",
    publishDate: "2026-08-14",
    readTime: "5 min read",
    excerpt: "For pilgrims travelling from Madinah, Dhul Hulaifah (Abyar Ali) is the Miqat stop before continuing to Makkah.",
    content: [
      { type: "p", text: "If your Umrah journey starts in Madinah, Dhul Hulaifah — commonly known as Abyar Ali — is the Miqat point where you'll enter Ihram before the onward journey to Makkah." },
      { type: "h2", text: "Where it is" },
      { type: "p", text: "It sits a short distance outside Madinah, directly on the route towards Makkah, so it fits naturally into your [Makkah-Madinah transfer](/services/makkah-madinah-transfer/) without a detour." },
      { type: "h2", text: "What to expect at the stop" },
      { type: "p", text: "There are facilities for ablution and changing into Ihram clothing. Most pilgrims allow 30-45 minutes here to change, pray two rak'ahs, and make the intention before continuing." },
      { type: "h2", text: "Why a private transfer helps here" },
      { type: "p", text: "On a shared bus or shuttle, this stop is often rushed to keep to a fixed schedule. With a private vehicle, your driver waits for you — no pressure to hurry through a moment that deserves your full attention." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
    ],
    relatedPosts: ["miqat-points-explained", "entering-ihram-what-to-know"],
  },
  {
    slug: "entering-ihram-what-to-know",
    title: "Entering Ihram: What to Know Before Your Miqat Stop",
    metaDescription:
      "Practical tips for a smooth Miqat stop — what to bring, what to wear, and how to plan your transport around it.",
    keywords: ["entering ihram", "miqat tips", "ihram preparation"],
    category: "Miqat & Ihram",
    publishDate: "2026-08-15",
    readTime: "5 min read",
    excerpt: "A few practical things to prepare before you reach your Miqat stop, so the process is calm rather than rushed.",
    content: [
      { type: "p", text: "Entering the state of Ihram is a significant moment in your Umrah journey, and a little preparation beforehand makes the actual Miqat stop far smoother." },
      { type: "h2", text: "Before you leave your hotel" },
      { type: "ul", items: [
        "Trim nails and remove unwanted hair beforehand, as this shouldn't be done after entering Ihram",
        "Shower and apply any permitted fragrance before changing, not after",
        "Pack your Ihram clothing where it's easy to reach, not buried at the bottom of your luggage",
      ] },
      { type: "h2", text: "For men" },
      { type: "p", text: "Two unstitched white sheets — one wrapped around the waist, one over the shoulder. See our [full Ihram guide for men and women](/blog/ihram-guide-men-women/) for more detail on what's permitted and what to avoid once you're in Ihram." },
      { type: "h2", text: "For women" },
      { type: "p", text: "Women don't wear a specific Ihram garment — regular modest clothing that covers appropriately is worn, without a face veil or gloves." },
      { type: "h2", text: "Timing your stop" },
      { type: "p", text: "Build in enough time at your Miqat rather than treating it as a quick pit stop — most pilgrims are glad they weren't rushed. Our drivers wait for as long as you need. See our [Miqat points guide](/blog/miqat-points-explained/) to confirm which stop applies to your route." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
    ],
    relatedPosts: ["miqat-points-explained", "dhul-hulaifah-miqat-guide", "ihram-guide-men-women"],
  },
  {
    slug: "umrah-group-travel-guide",
    title: "Umrah Group Travel: How to Organize Transport for Large Families",
    metaDescription:
      "Planning Umrah transport for a large family or group? Here's how to think about vehicle sizing, luggage, and coordinating everyone's schedule.",
    keywords: ["umrah group travel", "family umrah transport", "large group umrah taxi"],
    category: "Group & Family Travel",
    publishDate: "2026-08-16",
    readTime: "6 min read",
    excerpt: "Coordinating transport for a large family or group takes a bit more planning — here's how to get it right the first time.",
    content: [
      { type: "p", text: "Travelling for Umrah as a large family or group brings real benefits — shared costs, company, and the experience of performing the rituals together. It also means transport planning needs a bit more thought than a solo trip." },
      { type: "h2", text: "Sizing your vehicles correctly" },
      { type: "p", text: "The most common mistake is underestimating luggage. A van rated for 7 passengers may not comfortably fit 7 passengers AND a full set of suitcases — always mention your expected luggage when booking, not just headcount. See our guide on [choosing the right vehicle](/blog/choosing-vehicle-umrah-group/) for a fuller breakdown." },
      { type: "h2", text: "One coordinator, one point of contact" },
      { type: "p", text: "For groups larger than a single family, it helps enormously to have one person as the single point of contact for all transport arrangements — confirming pickup times, sharing the group's flight details, and relaying any changes. This avoids confusion when multiple people are messaging separately." },
      { type: "h2", text: "Splitting a large group across vehicles" },
      { type: "p", text: "For groups of 15 or more, we typically recommend a Coaster bus for everyone travelling together, or splitting across two vans if the group prefers more flexibility to arrive separately. Either way, we assign a coordinating driver so all vehicles stay in contact during the journey." },
      { type: "p", text: "See our [Group Packages](/services/group-packages/) or [book online](/book-online/) with your total passenger and luggage count, and we'll recommend the right combination of vehicles." },
    ],
    relatedServices: [
      { label: "Group Packages", href: "/services/group-packages/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["choosing-vehicle-umrah-group", "umrah-with-kids-family-tips", "umrah-budget-guide"],
  },
  {
    slug: "choosing-vehicle-umrah-group",
    title: "Choosing the Right Vehicle for Your Umrah Group",
    metaDescription:
      "Sedan, van, or bus? A practical breakdown of which vehicle suits your Umrah group size, luggage, and comfort needs.",
    keywords: ["umrah vehicle choice", "best vehicle for umrah group", "umrah van vs bus"],
    category: "Group & Family Travel",
    publishDate: "2026-08-17",
    readTime: "5 min read",
    excerpt: "From a 3-seater sedan to a 25-seater coach — here's how to match the vehicle to your group size and needs.",
    content: [
      { type: "p", text: "One question we get asked constantly is simply: what vehicle do I actually need? Here's a straightforward breakdown by group size." },
      { type: "h2", text: "1-3 passengers" },
      { type: "p", text: "A sedan like the Toyota Camry or Ford Taurus is comfortable and economical. For a more premium ride, the Mercedes S-Class or BMW 7 Series adds extra comfort for longer intercity trips." },
      { type: "h2", text: "4-7 passengers" },
      { type: "p", text: "A van such as the Hyundai Staria, Toyota Hiace, or Mercedes Vito gives families room to spread out with luggage, without needing two separate vehicles." },
      { type: "h2", text: "8-11 passengers" },
      { type: "p", text: "Larger vans like the extended Toyota Hiace work well for bigger families or small groups travelling together with a moderate amount of luggage." },
      { type: "h2", text: "12+ passengers" },
      { type: "p", text: "For larger delegations, a Toyota Coaster (up to 17 seats) or full-size bus (up to 25 seats) keeps the whole group together in one vehicle with a single driver, which is far easier to coordinate than multiple cars." },
      { type: "p", text: "Not sure which fits your situation? See the [full fleet](/fleet/) with exact seating and luggage capacity, or [tell us your group size](/book-online/) and we'll recommend the right option." },
    ],
    relatedServices: [
      { label: "View Our Fleet", href: "/fleet/" },
      { label: "Group Packages", href: "/services/group-packages/" },
    ],
    relatedPosts: ["umrah-group-travel-guide", "umrah-with-kids-family-tips"],
  },
  {
    slug: "first-time-umrah-guide",
    title: "First-Time Umrah Guide: Everything You Need to Know",
    metaDescription:
      "A beginner's guide to performing Umrah for the first time — what to expect, how to prepare, and practical tips for a smooth trip.",
    keywords: ["first time umrah guide", "umrah for beginners", "how to perform umrah"],
    category: "Umrah Planning",
    publishDate: "2026-08-18",
    readTime: "8 min read",
    excerpt: "Performing Umrah for the first time can feel overwhelming to plan — here's a practical starting point covering the essentials.",
    content: [
      { type: "p", text: "If this is your first Umrah, it's natural to have questions about how everything fits together — visas, flights, rituals, and logistics on the ground. This guide covers the practical basics to help you plan with confidence." },
      { type: "h2", text: "Before you travel" },
      { type: "ul", items: [
        "Confirm your Umrah visa well ahead of your travel dates — see our [Umrah visa guide](/blog/umrah-visa-guide/)",
        "Book flights into Jeddah or Madinah depending on your planned route",
        "Arrange your hotel near the Haram in whichever city you land first",
        "Pack according to our [Umrah packing list](/blog/umrah-packing-list/)",
      ] },
      { type: "h2", text: "The basic sequence of rituals" },
      { type: "p", text: "At a high level, Umrah involves entering Ihram at your Miqat, performing Tawaf (circling the Kaaba seven times), Sa'i (walking between Safa and Marwah), and finally Halq or Taqsir (shaving or trimming the hair). For the specific steps and any questions about your particular situation, it's always best to consult a knowledgeable scholar or your group's guide — see our [step-by-step overview](/blog/umrah-step-by-step-guide/) for the general sequence." },
      { type: "h2", text: "Getting around" },
      { type: "p", text: "Between the airport, your hotel, the Haram, and any Ziyarat sites you'd like to visit, transport is one of the more practical things to plan in advance. Arranging a [private transfer](/book-online/) rather than relying on taxis found on the spot means one less thing to figure out after a long flight." },
      { type: "h2", text: "First-timer tips" },
      { type: "ul", items: [
        "Arrive a day before any major ritual so you're not rushed or jet-lagged",
        "Stay hydrated — the climate is far drier and hotter than most visitors are used to",
        "Keep your passport and visa documents on you at all times, not packed in checked luggage",
        "Save our WhatsApp number before you travel, so help is one message away",
      ] },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
      { label: "Airport Transfer Services", href: "/services/airport-transfer/" },
    ],
    relatedPosts: ["umrah-packing-list", "umrah-visa-guide", "umrah-step-by-step-guide"],
  },
  {
    slug: "best-time-of-year-for-umrah",
    title: "Best Time of Year to Perform Umrah",
    metaDescription:
      "Weather, crowd levels and cost all shift throughout the year — here's how to choose the best time of year for your Umrah trip.",
    keywords: ["best time for umrah", "umrah season", "when to perform umrah"],
    category: "Umrah Planning",
    publishDate: "2026-08-19",
    readTime: "6 min read",
    excerpt: "Weather, crowds and pricing all vary significantly through the year — here's how to weigh them against your own priorities.",
    content: [
      { type: "p", text: "Umrah can be performed at any time of year, but the experience differs quite a bit depending on the season you choose — mainly due to weather, crowd levels, and how busy the Ramadan and Hajj periods get." },
      { type: "h2", text: "Winter months (roughly November-February)" },
      { type: "p", text: "Cooler, more comfortable weather for walking and standing for long periods, especially for elderly travellers. This is a popular window for exactly that reason, so book accommodation and transport early." },
      { type: "h2", text: "Ramadan" },
      { type: "p", text: "Deeply spiritually significant, but also the busiest period of the year outside Hajj — expect much larger crowds around the Haram, and book everything, including transport, well in advance." },
      { type: "h2", text: "Summer months (roughly May-September)" },
      { type: "p", text: "Considerably hotter, particularly for outdoor Ziyarat visits, but generally quieter and often more affordable. If you travel in summer, plan outdoor activities for early morning and stay well hydrated." },
      { type: "h2", text: "Our recommendation" },
      { type: "p", text: "There's no universally 'best' time — it depends on your tolerance for heat and crowds versus your preference for a quieter, more affordable trip. Whichever season you choose, [book your transport early](/book-online/), since availability tightens up considerably around Ramadan." },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["umrah-budget-guide", "first-time-umrah-guide", "tips-for-elderly-disabled-pilgrims"],
  },
  {
    slug: "umrah-packing-list",
    title: "Umrah Packing List: What to Bring",
    metaDescription:
      "A practical Umrah packing checklist covering Ihram clothing, documents, health essentials and everyday items.",
    keywords: ["umrah packing list", "what to pack for umrah", "umrah checklist"],
    category: "Umrah Planning",
    publishDate: "2026-08-20",
    readTime: "6 min read",
    excerpt: "A practical checklist so nothing essential gets left behind — from Ihram clothing to documents and everyday comfort items.",
    content: [
      { type: "p", text: "Packing for Umrah is a mix of religious essentials and ordinary travel practicality. Here's a checklist covering both." },
      { type: "h2", text: "Documents" },
      { type: "ul", items: [
        "Passport with your Umrah visa (plus photocopies, stored separately)",
        "Flight and hotel booking confirmations",
        "Travel insurance details",
        "Emergency contact numbers, including your transport provider's WhatsApp",
      ] },
      { type: "h2", text: "Ihram and clothing" },
      { type: "ul", items: [
        "Two sets of Ihram cloth for men (in case one needs washing)",
        "Modest, comfortable clothing for women",
        "Comfortable, easy-to-remove sandals for frequent wudu",
        "A light jacket or shawl for air-conditioned spaces",
      ] },
      { type: "h2", text: "Health and comfort" },
      { type: "ul", items: [
        "Any personal medication, clearly labelled, in hand luggage",
        "Sunscreen and a small umbrella or cap for sun protection",
        "A refillable water bottle",
        "Basic first-aid items — blister plasters are more useful than you'd expect",
      ] },
      { type: "h2", text: "Everyday essentials" },
      { type: "ul", items: [
        "Phone charger and a local SIM or eSIM for data",
        "Small daypack for carrying essentials to the Haram",
        "Unscented soap and toiletries (avoid scented products while in Ihram)",
      ] },
      { type: "p", text: "Once you've packed, the next thing worth arranging is your [airport pickup](/book-online/) so you're not managing luggage and transport logistics on arrival after a long flight." },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["first-time-umrah-guide", "ihram-guide-men-women", "umrah-budget-guide"],
  },
  {
    slug: "umrah-budget-guide",
    title: "Umrah Budget Guide: How Much Does It Cost",
    metaDescription:
      "A breakdown of the main cost categories for an Umrah trip — flights, visa, accommodation and local transport — to help you budget realistically.",
    keywords: ["umrah cost", "umrah budget", "how much does umrah cost"],
    category: "Umrah Planning",
    publishDate: "2026-08-21",
    readTime: "6 min read",
    excerpt: "Flights, visa, hotels and local transport all add up differently depending on when and how you travel — here's how to budget sensibly.",
    content: [
      { type: "p", text: "Umrah costs vary enormously depending on your home country, travel dates, and choice of accommodation. Rather than quoting one number that won't apply to most readers, here's how to break the budget down into its real components." },
      { type: "h2", text: "Flights" },
      { type: "p", text: "Usually the single largest cost, and highly seasonal — prices rise sharply around Ramadan and school holiday periods. Booking several months ahead generally saves the most." },
      { type: "h2", text: "Visa" },
      { type: "p", text: "See our [Umrah visa guide](/blog/umrah-visa-guide/) for current entry requirements — costs and processes vary by nationality." },
      { type: "h2", text: "Accommodation" },
      { type: "p", text: "Hotels within walking distance of the Haram in both cities command a significant premium over those a short drive away. If budget is a priority, staying slightly further out and arranging reliable transport can be more cost-effective than paying for a room at the door of the Haram." },
      { type: "h2", text: "Local transport" },
      { type: "p", text: "Airport transfers, the Makkah-Madinah intercity leg, and any Ziyarat tours are worth budgeting for as a fixed, known cost rather than negotiating on the spot — [WhatsApp us](/book-online/) for a transparent quote before you travel, so it's one less unknown in your budget." },
      { type: "h2", text: "Ways to manage cost without cutting corners" },
      { type: "ul", items: [
        "Travel outside Ramadan and peak school holidays if your schedule allows",
        "Book transport in advance rather than relying on higher on-the-spot taxi rates",
        "Consider a hotel slightly further from the Haram if it meaningfully reduces cost",
        "Travel as a group to share vehicle and package costs",
      ] },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
      { label: "Group Packages", href: "/services/group-packages/" },
    ],
    relatedPosts: ["umrah-visa-guide", "best-time-of-year-for-umrah", "umrah-group-travel-guide"],
  },
  {
    slug: "umrah-visa-guide",
    title: "Umrah Visa Guide",
    metaDescription:
      "An overview of how Umrah visas generally work, who needs one, and where to check current requirements before you travel.",
    keywords: ["umrah visa guide", "umrah visa requirements", "how to get umrah visa"],
    category: "Umrah Planning",
    publishDate: "2026-08-22",
    readTime: "5 min read",
    excerpt: "Visa rules and processes can change, so here's a general overview and where to check the current requirements before booking flights.",
    content: [
      { type: "p", text: "Umrah visa processes have become considerably more streamlined in recent years, largely through official digital platforms, but exact requirements depend heavily on your nationality and can change. Always confirm current rules through an official source before finalising travel plans." },
      { type: "h2", text: "General routes to an Umrah visa" },
      { type: "ul", items: [
        "Official government Umrah visa platforms and authorised agents",
        "An eligible tourist e-visa, which in many cases also permits Umrah",
        "Through a licensed Umrah travel agency in your home country, who handle the application on your behalf",
      ] },
      { type: "h2", text: "What you'll typically need" },
      { type: "ul", items: [
        "A passport valid for several months beyond your travel dates",
        "A recent passport-style photo meeting the platform's specifications",
        "Proof of return flights and accommodation in many cases",
        "For women under a certain age, a Mahram or documented group travel arrangement may be required — check current rules for your situation",
      ] },
      { type: "h2", text: "Our advice" },
      { type: "p", text: "Because visa rules are updated periodically, don't rely on secondhand information — check the official government Umrah visa platform or your embassy directly, and start the process well ahead of your intended travel dates. Once your visa and flights are confirmed, the next step is arranging your [airport transfer](/book-online/) so everything is ready before you land." },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["first-time-umrah-guide", "umrah-budget-guide"],
  },
  {
    slug: "ihram-guide-men-women",
    title: "What to Wear During Umrah: Ihram Guide for Men & Women",
    metaDescription:
      "A guide to Ihram clothing requirements for men and women, and what's permitted or best avoided during the state of Ihram.",
    keywords: ["ihram guide", "ihram clothing men women", "what to wear umrah"],
    category: "Umrah Planning",
    publishDate: "2026-08-23",
    readTime: "5 min read",
    excerpt: "Ihram requirements differ for men and women — here's a clear, practical overview of what to wear and what to avoid.",
    content: [
      { type: "p", text: "Ihram clothing rules differ between men and women, and knowing the practical basics ahead of time makes your Miqat stop far less stressful." },
      { type: "h2", text: "For men" },
      { type: "p", text: "Two pieces of unstitched, seamless white cloth — one wrapped around the waist and lower body, one draped over the shoulder. Regular stitched clothing, including underwear seams in some views, footwear that covers the ankle bones, and headwear are avoided while in Ihram — for specific rulings on your situation, consult a knowledgeable scholar or your group's guide." },
      { type: "h2", text: "For women" },
      { type: "p", text: "Women wear their normal modest clothing — there's no special Ihram garment. The main restrictions are on covering the face with a niqab and wearing gloves while in the state of Ihram." },
      { type: "h2", text: "Practical tips" },
      { type: "ul", items: [
        "Pack a spare set of Ihram cloth for men in case of spills or the need to wash",
        "Choose breathable, comfortable fabric given the climate",
        "Bring a small bag to carry regular clothes and shoes after changing at the Miqat",
      ] },
      { type: "p", text: "For more on the practical side of your Miqat stop, see our guide on [entering Ihram](/blog/entering-ihram-what-to-know/)." },
    ],
    relatedServices: [
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
    ],
    relatedPosts: ["entering-ihram-what-to-know", "umrah-packing-list", "miqat-points-explained"],
  },
  {
    slug: "umrah-step-by-step-guide",
    title: "Umrah Step-by-Step Guide",
    metaDescription:
      "A general overview of the sequence of Umrah rituals, from entering Ihram to Tawaf, Sa'i and Halq or Taqsir.",
    keywords: ["umrah step by step", "umrah rituals order", "how to perform umrah steps"],
    category: "Umrah Planning",
    publishDate: "2026-08-24",
    readTime: "6 min read",
    excerpt: "A general overview of how the Umrah rituals fit together, from Ihram through to Tawaf, Sa'i and Halq or Taqsir.",
    content: [
      { type: "p", text: "This is a general, practical overview of how the Umrah rituals sequence together. For detailed rulings specific to your situation, please consult a knowledgeable scholar or your group's guide — this guide is meant to help you understand the flow of the day, not as a religious ruling." },
      { type: "h2", text: "1. Entering Ihram at the Miqat" },
      { type: "p", text: "Before crossing your designated Miqat boundary, you shower, put on Ihram clothing, and make the intention (niyyah) for Umrah. See our [Miqat points guide](/blog/miqat-points-explained/) for which boundary applies to your route." },
      { type: "h2", text: "2. Tawaf" },
      { type: "p", text: "Upon arriving at Masjid al-Haram, pilgrims perform Tawaf — circling the Kaaba seven times, starting and ending at the Black Stone corner." },
      { type: "h2", text: "3. Sa'i" },
      { type: "p", text: "Following Tawaf, pilgrims perform Sa'i — walking seven times between the hills of Safa and Marwah, now enclosed within an air-conditioned corridor of the Haram complex." },
      { type: "h2", text: "4. Halq or Taqsir" },
      { type: "p", text: "Umrah concludes with either Halq (shaving the head, for men) or Taqsir (trimming a portion of the hair), after which the restrictions of Ihram are lifted." },
      { type: "h2", text: "Planning around it" },
      { type: "p", text: "Once your rituals are complete, many pilgrims move on to Ziyarat sites or travel onward to the other holy city — see our [Ziyarat guide](/blog/complete-ziyarat-guide-makkah/) or [Makkah-Madinah transfer guide](/blog/makkah-to-madinah-by-road-guide/) for what comes next." },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["miqat-points-explained", "complete-ziyarat-guide-makkah", "first-time-umrah-guide"],
  },
  {
    slug: "tips-for-elderly-disabled-pilgrims",
    title: "Tips for Elderly and Disabled Pilgrims During Umrah",
    metaDescription:
      "Practical advice for making Umrah more comfortable for elderly or mobility-impaired pilgrims, from transport to timing.",
    keywords: ["umrah for elderly", "umrah wheelchair accessibility", "disabled pilgrims umrah tips"],
    category: "Umrah Planning",
    publishDate: "2026-08-25",
    readTime: "6 min read",
    excerpt: "A few adjustments to timing, transport and pacing can make a significant difference for elderly or mobility-impaired pilgrims.",
    content: [
      { type: "p", text: "Umrah is physically demanding even for fit, younger travellers — long walks, standing, and heat. With some planning, it can still be a comfortable and manageable journey for elderly or mobility-impaired pilgrims." },
      { type: "h2", text: "Timing your activities" },
      { type: "p", text: "Plan Tawaf, Sa'i and any Ziyarat visits for early morning or late evening when it's cooler and less crowded, rather than the midday heat. See our guide on [the best time to visit Masjid al-Haram](/blog/best-time-to-visit-masjid-al-haram/) for quieter windows." },
      { type: "h2", text: "Wheelchair services" },
      { type: "p", text: "Masjid al-Haram offers wheelchair services and dedicated pathways for Tawaf and Sa'i for those who need them — it's worth asking about this at your hotel or with your group leader ahead of time." },
      { type: "h2", text: "Transport comfort" },
      { type: "p", text: "For longer transfers like [Makkah to Madinah](/blog/makkah-to-madinah-by-road-guide/), a more spacious, comfortable vehicle with easy entry and exit makes a real difference over several hours on the road. Mention any mobility needs when you [book your transfer](/book-online/) so we can match the right vehicle." },
      { type: "h2", text: "General tips" },
      { type: "ul", items: [
        "Pace rituals over more than one visit rather than rushing everything into a single day",
        "Bring any regular medication in clearly labelled hand luggage",
        "Travel with a companion where possible for both religious and practical support",
        "Stay well hydrated throughout, even when not thirsty",
      ] },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["best-time-to-visit-masjid-al-haram", "makkah-to-madinah-by-road-guide", "umrah-with-kids-family-tips"],
  },
  {
    slug: "where-to-stay-in-makkah",
    title: "Where to Stay in Makkah: Hotel Guide Near Haram",
    metaDescription:
      "How to choose where to stay in Makkah — proximity to the Haram, budget trade-offs, and how transport can help if you stay further out.",
    keywords: ["where to stay in makkah", "makkah hotels near haram", "makkah accommodation guide"],
    category: "City Guides",
    publishDate: "2026-08-26",
    readTime: "5 min read",
    excerpt: "Proximity to the Haram comes at a premium — here's how to think about the trade-off between location and budget.",
    content: [
      { type: "p", text: "Choosing where to stay in Makkah usually comes down to one main trade-off: how close to Masjid al-Haram do you want to be, and how much are you willing to pay for that proximity?" },
      { type: "h2", text: "Staying within walking distance" },
      { type: "p", text: "Hotels in the Abraj al-Bait / clock tower area and the surrounding zone offer the shortest possible walk to the Haram, ideal for elderly travellers or anyone planning multiple daily visits. This convenience comes at a significant price premium, especially during Ramadan." },
      { type: "h2", text: "Staying a short drive away" },
      { type: "p", text: "Areas like Aziziyah offer considerably lower rates while still being a manageable short drive from the Haram. If you go this route, arranging reliable transport for your daily trips matters more — [book a driver](/book-online/) who can take you back and forth on your own schedule rather than relying on inconsistent shared shuttles." },
      { type: "h2", text: "What to consider" },
      { type: "ul", items: [
        "How many times a day you plan to visit the Haram",
        "Whether you're travelling with elderly or very young family members",
        "Your overall trip budget and how much of it you want allocated to accommodation versus other costs",
      ] },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["umrah-budget-guide", "best-time-to-visit-masjid-al-haram"],
  },
  {
    slug: "where-to-stay-in-madinah",
    title: "Where to Stay in Madinah: Best Areas Near Masjid an-Nabawi",
    metaDescription:
      "A guide to choosing accommodation in Madinah — how far from Masjid an-Nabawi is reasonable, and what to expect at each distance.",
    keywords: ["where to stay in madinah", "madinah hotels near masjid nabawi", "madinah accommodation"],
    category: "City Guides",
    publishDate: "2026-08-27",
    readTime: "5 min read",
    excerpt: "Madinah's hotel zones are generally more compact than Makkah's — here's how to choose the right area for your stay.",
    content: [
      { type: "p", text: "Madinah's hotel district around Masjid an-Nabawi is somewhat more compact and walkable than Makkah's, which makes choosing accommodation a little more straightforward." },
      { type: "h2", text: "The central zone" },
      { type: "p", text: "Hotels directly surrounding the mosque offer a short walk to all five daily prayers, which many pilgrims consider well worth the higher rate during their time in Madinah." },
      { type: "h2", text: "A short distance out" },
      { type: "p", text: "Slightly further hotels still offer reasonable walking distance for most travellers, at a noticeably lower cost — useful if you're balancing a longer overall trip budget." },
      { type: "h2", text: "Getting around either way" },
      { type: "p", text: "Wherever you stay, you'll likely want transport for your [Madinah Ziyarat day](/blog/madinah-ziyarat-guide/) and your onward [transfer to Makkah](/services/makkah-madinah-transfer/) — arranging both in advance means one less thing to think about during your stay." },
    ],
    relatedServices: [
      { label: "Madinah Ziyarat Tours", href: "/services/ziyarat-tours/" },
      { label: "Makkah ↔ Madinah Transfer", href: "/services/makkah-madinah-transfer/" },
    ],
    relatedPosts: ["madinah-ziyarat-guide", "madinah-airport-transfer-guide"],
  },
  {
    slug: "best-time-to-visit-masjid-al-haram",
    title: "Best Time to Visit Masjid al-Haram (Avoiding Crowds)",
    metaDescription:
      "When is Masjid al-Haram least crowded? A practical guide to timing your visits for a calmer, more comfortable experience.",
    keywords: ["masjid al-haram crowds", "best time to visit haram", "quiet time makkah haram"],
    category: "City Guides",
    publishDate: "2026-08-28",
    readTime: "5 min read",
    excerpt: "Crowd levels at the Haram shift dramatically by time of day and season — here's how to plan around them.",
    content: [
      { type: "p", text: "Masjid al-Haram is rarely empty, but crowd levels swing significantly depending on the time of day, day of the week, and time of year — and knowing this can make a real difference to your comfort during Tawaf and Sa'i." },
      { type: "h2", text: "Quieter times of day" },
      { type: "p", text: "Late night through to just before Fajr tends to be noticeably calmer than daytime hours. The period right after Fajr, before the day's heat builds, is also a good window for elderly travellers." },
      { type: "h2", text: "Busier times" },
      { type: "p", text: "The hours around and between Maghrib and Isha are typically the busiest, especially on Fridays. During Ramadan, crowd levels increase substantially throughout, particularly in the final ten nights." },
      { type: "h2", text: "Planning your visits" },
      { type: "p", text: "If you have flexibility in your schedule, spreading your Tawaf visits across quieter windows rather than concentrating them at peak times makes the physical experience considerably easier — especially relevant if you're travelling with [elderly or mobility-impaired family members](/blog/tips-for-elderly-disabled-pilgrims/)." },
    ],
    relatedServices: [
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["tips-for-elderly-disabled-pilgrims", "where-to-stay-in-makkah"],
  },
  {
    slug: "public-transport-in-makkah",
    title: "Public Transport in Makkah: A Visitor's Guide",
    metaDescription:
      "How does getting around Makkah actually work — shuttle buses, taxis, and why most visitors prefer a private driver.",
    keywords: ["makkah public transport", "makkah taxi", "getting around makkah"],
    category: "City Guides",
    publishDate: "2026-08-29",
    readTime: "5 min read",
    excerpt: "A look at the transport options within Makkah itself, and why most visitors end up preferring a private driver for anything beyond walking distance.",
    content: [
      { type: "p", text: "Once you're settled in Makkah, getting around the city for anything beyond walking distance to the Haram usually means choosing between a few options." },
      { type: "h2", text: "Shuttle buses" },
      { type: "p", text: "Some hotels, particularly those a bit further from the Haram, run their own shuttle services on a fixed schedule. Convenient if the timing matches your plans, less so if it doesn't." },
      { type: "h2", text: "Street taxis" },
      { type: "p", text: "Available but inconsistent in availability and price, particularly during busy periods — negotiating a fare on the spot after a long day isn't most visitors' idea of a relaxing experience." },
      { type: "h2", text: "A private driver" },
      { type: "p", text: "For Ziyarat trips, airport transfers, or the intercity journey to Madinah, most visitors find a [pre-arranged private vehicle](/book-online/) far less stressful than figuring out local transport on the spot — a fixed, agreed price and a driver who's waiting for you rather than the other way around." },
    ],
    relatedServices: [
      { label: "Ziyarat Tours", href: "/services/ziyarat-tours/" },
      { label: "Book Online", href: "/book-online/" },
    ],
    relatedPosts: ["complete-ziyarat-guide-makkah", "where-to-stay-in-makkah"],
  },
  {
    slug: "umrah-with-kids-family-tips",
    title: "Umrah with Kids: Family Travel Tips",
    metaDescription:
      "Practical tips for travelling to Umrah with children — what to pack, how to plan the pace, and transport considerations for families.",
    keywords: ["umrah with kids", "umrah family travel tips", "traveling to umrah with children"],
    category: "City Guides",
    publishDate: "2026-08-30",
    readTime: "6 min read",
    excerpt: "Travelling with children adds a few extra considerations to your Umrah plan — here's how to make it manageable for the whole family.",
    content: [
      { type: "p", text: "Umrah with children is entirely manageable with a bit of extra planning around pacing, comfort, and having the right vehicle for everyone plus the extra luggage that inevitably comes with kids." },
      { type: "h2", text: "Packing for children" },
      { type: "p", text: "Beyond the standard [Umrah packing list](/blog/umrah-packing-list/), bring extra snacks, entertainment for waiting periods, and any comfort items that help younger children settle in an unfamiliar environment." },
      { type: "h2", text: "Pacing the rituals" },
      { type: "p", text: "Rather than trying to complete everything in one long day, consider spreading Tawaf, Sa'i and any Ziyarat visits across a couple of days, with rest breaks in between — much easier on both children and accompanying adults." },
      { type: "h2", text: "Choosing the right vehicle" },
      { type: "p", text: "Families often need more space than headcount alone suggests, once you factor in car seats, strollers and extra luggage. A van like the Hyundai Staria or Toyota Hiace usually gives families the room they need — see our guide on [choosing the right vehicle](/blog/choosing-vehicle-umrah-group/)." },
      { type: "h2", text: "Booking ahead" },
      { type: "p", text: "[Book your family's transport](/book-online/) with your exact passenger count including children, so the vehicle assigned actually has room for everyone comfortably." },
    ],
    relatedServices: [
      { label: "Group Packages", href: "/services/group-packages/" },
      { label: "View Our Fleet", href: "/fleet/" },
    ],
    relatedPosts: ["choosing-vehicle-umrah-group", "umrah-packing-list", "tips-for-elderly-disabled-pilgrims"],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(post: BlogPost): BlogPost[] {
  return post.relatedPosts
    .map((slug) => getPostBySlug(slug))
    .filter((p): p is BlogPost => !!p);
}
